# FROM mcr.microsoft.com/dotnet/core/runtime:2.2
# WORKDIR /app
# COPY /app /app
# ENTRYPOINT [ "dotnet" , "OccBooking.Web.dll"]

# FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
# WORKDIR /app

# Copy csproj and restore as distinct layers
# COPY *.csproj ./
# RUN dotnet restore

# # Copy everything else and build
# # COPY . ../
# # RUN dotnet publish -c Release -o out

# Build runtime image
# FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
#dotnet publish -c release -o app/ .
#docker build -t occbooking .
#docker run -p
FROM microsoft/dotnet:2.2.0-aspnetcore-runtime AS base
WORKDIR /app
COPY /app /app 
ENTRYPOINT ["dotnet", "OccBooking.Web.dll"]