@url = https://localhost:44308/api/
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYzQ4ODIwMC0yMGMyLTQ5NmQtYTJjMi05ZGM2N2RkNDJjODUiLCJqdGkiOiJkY2Y2ODNkZC05ZGY3LTQ1NDItYjY4My0zNjhiZGVmYmNmODUiLCJpYXQiOjE1NzE0MTI2NTcsInVzZXJJZCI6ImVjNDg4MjAwLTIwYzItNDk2ZC1hMmMyLTlkYzY3ZGQ0MmM4NSIsIm5iZiI6MTU3MTQxMjY1NiwiZXhwIjoxNTcxNDE5ODU2LCJpc3MiOiJPY2NCb29raW5nIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwLyJ9.k_bY3dr7z-bcbj1sn-RdtaDnnpqCGyVQME9xqoGYb0Q
@ownerId = e8775e65-466b-43bf-b99c-daa84182c440
POST {{url}}auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "email": "string@xd",
  "phoneNumber": "505817433",
  "userName": "string123456",
  "password": "string",
  "confirmPassword": "string"
}

POST {{url}}auth/login HTTP/1.1
content-type: application/json

{
  "userName": "string123456",
  "password": "string",
}

GET {{url}}auth/user HTTP/1.1
authorization: Bearer {{authToken}}


GET {{url}}places HTTP/1.1

POST {{url}}{{ownerId}}/places HTTP/1.1
content-type: application/json
authorization: Bearer {{authToken}}

{
  "name": "string",
  "hasRooms": true,
  "costPerPerson": 1,
  "description": "string",
  "street": "sezamkowa",
  "city": "string",
  "zipCode": "11-111",
  "province": "śląskie"
}