@url = https://localhost:44308/api/
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYXEyNDAyIiwianRpIjoiOWJhZjliZTktNjEyMS00MjRhLTlhMDgtNWY3OTQ1OGZlZjEyIiwiaWF0IjoxNTY5MDg2MDAwLCJuYmYiOjE1NjkwODYwMDAsImV4cCI6MTU2OTA5MzIwMH0.3NZTCWSyf-PHhFAw-qi78fF0k7BgtEgUY_2rfZb6JAw

POST {{url}}auth/register HTTP/1.1
content-type: application/json
{
  "firstName": "string",
  "lastName": "string",
  "email": "string@xD.com",
  "phoneNumber": "505817433",
  "userName": "string1234",
  "password": "string",
  "confirmPassword": "string"
}

POST {{url}}auth/login HTTP/1.1
content-type: application/json

{
  "userName": "maq2402",
  "password": "asd",
}

GET {{url}}auth/user HTTP/1.1
authorization: Bearer {{authToken}}