@url = https://localhost:44308/api/
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYzQ4ODIwMC0yMGMyLTQ5NmQtYTJjMi05ZGM2N2RkNDJjODUiLCJqdGkiOiIwMjkzNTRjZC02N2RjLTRlYzYtODU3OC1hMjU3ZmQ1ZDVkOGQiLCJpYXQiOjE1NzA4ODEzODcsInVzZXJJZCI6ImVjNDg4MjAwLTIwYzItNDk2ZC1hMmMyLTlkYzY3ZGQ0MmM4NSIsIm5iZiI6MTU3MDg4MTM4NiwiZXhwIjoxNTcwODg4NTg2LCJpc3MiOiJPY2NCb29raW5nIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwLyJ9.UUzcF9HxG5vjpDLw5S-DIUbxIj-SyttHTty7wl-B7ik

POST {{url}}auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "email": "string@xd",
  "phoneNumber": "505817433",
  "userName": "string123456",
  "password": "string",
  "confirmPassword": "string"
}

POST {{url}}auth/login HTTP/1.1
content-type: application/json

{
  "userName": "string123456",
  "password": "string",
}

GET {{url}}auth/user HTTP/1.1
authorization: Bearer {{authToken}}